[package]
name = "custom-type"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = "0.99.18"
regex = "1.10.5"
serde = {version = "1.0.204", features = ["derive"]}


[dev-dependencies]
serde_json = "1.0.120"